#spring:
#  application:
#    name: eureka-service
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#logging:
#  pattern:
#    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}